// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject3
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public partial class UIMap
    {
        
        /// <summary>
        /// rong65 ra
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WinEdit uIAllwork1sgmailcomEdit = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllwork1sgmailcomEdit;
            #endregion

            // Verify that the 'ControlType' property of 'allwork1s@gmail.com' text box equals '1'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIAllwork1sgmailcomEditControlType, uIAllwork1sgmailcomEdit.ControlType.ToString(), "failed");
        }
        
        /// <summary>
        /// chieurong
        /// </summary>
        public void AssertMethod2()
        {
            #region Variable Declarations
            WinGroup uIAllWork1sGoogleChromGroup = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllWork1sGoogleChromGroup;
            #endregion

            // Verify that the 'ControlType' property of 'AllWork1s - Google Chrome' group equals '2'
            Assert.AreEqual(this.AssertMethod2ExpectedValues.UIAllWork1sGoogleChromGroupControlType, uIAllWork1sGoogleChromGroup.ControlType.ToString(), "chieurong");
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual AssertMethod2ExpectedValues AssertMethod2ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod2ExpectedValues == null))
                {
                    this.mAssertMethod2ExpectedValues = new AssertMethod2ExpectedValues();
                }
                return this.mAssertMethod2ExpectedValues;
            }
        }
        
        public UIAllWork1sGoogleChromWindow UIAllWork1sGoogleChromWindow
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromWindow == null))
                {
                    this.mUIAllWork1sGoogleChromWindow = new UIAllWork1sGoogleChromWindow();
                }
                return this.mUIAllWork1sGoogleChromWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private AssertMethod2ExpectedValues mAssertMethod2ExpectedValues;
        
        private UIAllWork1sGoogleChromWindow mUIAllWork1sGoogleChromWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'allwork1s@gmail.com' text box equals '1'
        /// </summary>
        public string UIAllwork1sgmailcomEditControlType = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class AssertMethod2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'AllWork1s - Google Chrome' group equals '2'
        /// </summary>
        public string UIAllWork1sGoogleChromGroupControlType = "2";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIAllWork1sGoogleChromWindow : WinWindow
    {
        
        public UIAllWork1sGoogleChromWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "AllWork1s - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIItemGroup mUIItemGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAllwork1sgmailcomEdit
        {
            get
            {
                if ((this.mUIAllwork1sgmailcomEdit == null))
                {
                    this.mUIAllwork1sgmailcomEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAllwork1sgmailcomEdit.SearchProperties[WinEdit.PropertyNames.Name] = "allwork1s@gmail.com";
                    this.mUIAllwork1sgmailcomEdit.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllwork1sgmailcomEdit;
            }
        }
        
        public WinGroup UIAllWork1sGoogleChromGroup
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromGroup == null))
                {
                    this.mUIAllWork1sGoogleChromGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIAllWork1sGoogleChromGroup.SearchProperties[WinControl.PropertyNames.Instance] = "3";
                    this.mUIAllWork1sGoogleChromGroup.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllWork1sGoogleChromGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAllwork1sgmailcomEdit;
        
        private WinGroup mUIAllWork1sGoogleChromGroup;
        #endregion
    }
}
