// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 16.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject2
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public partial class UIMap
    {
        
        /// <summary>
        /// dangnhap
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinControl uIAllWork1sGoogleChromDocument = this.UIAllWork1sGoogleChromWindow.UIChromeLegacyWindowWindow.UIAllWork1sGoogleChromDocument;
            WinEdit uIItemEdit = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIItemEdit;
            WinGroup uIAllWork1sGoogleChromGroup = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllWork1sGoogleChromGroup;
            WinText uIAllWork1sGoogleChromText = this.UIAllWork1sGoogleChromWindow.UIỨngViênTanhuynh1999MenuButton.UIAllWork1sGoogleChromText;
            WinText uIAllWork1sGoogleChromText1 = this.UIAllWork1sGoogleChromWindow.UIĐăngxuấtHyperlink.UIAllWork1sGoogleChromText;
            #endregion

            // Click 'AllWork1s - Google Chrome' document
            Mouse.Click(uIAllWork1sGoogleChromDocument, new Point(876, 337));

            // Click '******************' text box
            Mouse.Click(uIItemEdit, new Point(340, 24));

            // Click 'AllWork1s - Google Chrome' group
            Mouse.Click(uIAllWork1sGoogleChromGroup, new Point(421, 27));

            // Click 'AllWork1s - Google Chrome' label
            Mouse.Click(uIAllWork1sGoogleChromText, new Point(68, 11));

            // Click 'AllWork1s - Google Chrome' label
            Mouse.Click(uIAllWork1sGoogleChromText1, new Point(34, 1));
        }
        
        /// <summary>
        /// 1
        /// </summary>
        public void AssertMethod1()
        {
            #region Variable Declarations
            WinEdit uIAllwork1sgmailcomEdit = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllwork1sgmailcomEdit;
            #endregion

            // Verify that the 'ControlType' property of 'allwork1s@gmail.com' text box equals '1'
            Assert.AreEqual(this.AssertMethod1ExpectedValues.UIAllwork1sgmailcomEditControlType, uIAllwork1sgmailcomEdit.ControlType.ToString(), "failed");
        }
        
        /// <summary>
        /// a
        /// </summary>
        public void AssertMethod2()
        {
            #region Variable Declarations
            WinEdit uIAllwork1sgmailcomEdit = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllwork1sgmailcomEdit;
            #endregion

            // Verify that the 'Left' property of 'allwork1s@gmail.com' text box equals '2'
            Assert.AreEqual(this.AssertMethod2ExpectedValues.UIAllwork1sgmailcomEditLeft, uIAllwork1sgmailcomEdit.Left, "a");
        }
        
        /// <summary>
        /// dai ra
        /// </summary>
        public void AssertMethod3()
        {
            #region Variable Declarations
            WinGroup uIAllWork1sGoogleChromGroup1 = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllWork1sGoogleChromGroup1;
            #endregion

            // Verify that the 'AccessibleDescription' property of 'AllWork1s - Google Chrome' group equals '5'
            Assert.AreEqual(this.AssertMethod3ExpectedValues.UIAllWork1sGoogleChromGroup1AccessibleDescription, uIAllWork1sGoogleChromGroup1.AccessibleDescription, "failed");
        }
        
        /// <summary>
        /// cieu dai
        /// </summary>
        public void AssertMethod4()
        {
            #region Variable Declarations
            WinEdit uIAllwork1sgmailcomEdit = this.UIAllWork1sGoogleChromWindow.UIItemGroup.UIAllwork1sgmailcomEdit;
            #endregion

            // Verify that the 'AccessibleDescription' property of 'allwork1s@gmail.com' text box equals '6'
            Assert.AreEqual(this.AssertMethod4ExpectedValues.UIAllwork1sgmailcomEditAccessibleDescription, uIAllwork1sgmailcomEdit.AccessibleDescription, "chieu dai");
        }
        
        #region Properties
        public virtual AssertMethod1ExpectedValues AssertMethod1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod1ExpectedValues == null))
                {
                    this.mAssertMethod1ExpectedValues = new AssertMethod1ExpectedValues();
                }
                return this.mAssertMethod1ExpectedValues;
            }
        }
        
        public virtual AssertMethod2ExpectedValues AssertMethod2ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod2ExpectedValues == null))
                {
                    this.mAssertMethod2ExpectedValues = new AssertMethod2ExpectedValues();
                }
                return this.mAssertMethod2ExpectedValues;
            }
        }
        
        public virtual AssertMethod3ExpectedValues AssertMethod3ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod3ExpectedValues == null))
                {
                    this.mAssertMethod3ExpectedValues = new AssertMethod3ExpectedValues();
                }
                return this.mAssertMethod3ExpectedValues;
            }
        }
        
        public virtual AssertMethod4ExpectedValues AssertMethod4ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod4ExpectedValues == null))
                {
                    this.mAssertMethod4ExpectedValues = new AssertMethod4ExpectedValues();
                }
                return this.mAssertMethod4ExpectedValues;
            }
        }
        
        public UIAllWork1sGoogleChromWindow UIAllWork1sGoogleChromWindow
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromWindow == null))
                {
                    this.mUIAllWork1sGoogleChromWindow = new UIAllWork1sGoogleChromWindow();
                }
                return this.mUIAllWork1sGoogleChromWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod1ExpectedValues mAssertMethod1ExpectedValues;
        
        private AssertMethod2ExpectedValues mAssertMethod2ExpectedValues;
        
        private AssertMethod3ExpectedValues mAssertMethod3ExpectedValues;
        
        private AssertMethod4ExpectedValues mAssertMethod4ExpectedValues;
        
        private UIAllWork1sGoogleChromWindow mUIAllWork1sGoogleChromWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class AssertMethod1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'allwork1s@gmail.com' text box equals '1'
        /// </summary>
        public string UIAllwork1sgmailcomEditControlType = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class AssertMethod2ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Left' property of 'allwork1s@gmail.com' text box equals '2'
        /// </summary>
        public int UIAllwork1sgmailcomEditLeft = 2;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class AssertMethod3ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'AccessibleDescription' property of 'AllWork1s - Google Chrome' group equals '5'
        /// </summary>
        public string UIAllWork1sGoogleChromGroup1AccessibleDescription = "5";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod4'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class AssertMethod4ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'AccessibleDescription' property of 'allwork1s@gmail.com' text box equals '6'
        /// </summary>
        public string UIAllwork1sgmailcomEditAccessibleDescription = "6";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIAllWork1sGoogleChromWindow : WinWindow
    {
        
        public UIAllWork1sGoogleChromWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "AllWork1s - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIỨngViênTanhuynh1999MenuButton UIỨngViênTanhuynh1999MenuButton
        {
            get
            {
                if ((this.mUIỨngViênTanhuynh1999MenuButton == null))
                {
                    this.mUIỨngViênTanhuynh1999MenuButton = new UIỨngViênTanhuynh1999MenuButton(this);
                }
                return this.mUIỨngViênTanhuynh1999MenuButton;
            }
        }
        
        public UIĐăngxuấtHyperlink UIĐăngxuấtHyperlink
        {
            get
            {
                if ((this.mUIĐăngxuấtHyperlink == null))
                {
                    this.mUIĐăngxuấtHyperlink = new UIĐăngxuấtHyperlink(this);
                }
                return this.mUIĐăngxuấtHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIItemGroup mUIItemGroup;
        
        private UIỨngViênTanhuynh1999MenuButton mUIỨngViênTanhuynh1999MenuButton;
        
        private UIĐăngxuấtHyperlink mUIĐăngxuấtHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Chrome Legacy Window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_RenderWidgetHostHWND";
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIAllWork1sGoogleChromDocument
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromDocument == null))
                {
                    this.mUIAllWork1sGoogleChromDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIAllWork1sGoogleChromDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIAllWork1sGoogleChromDocument.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllWork1sGoogleChromDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIAllWork1sGoogleChromDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.SearchProperties[WinEdit.PropertyNames.Name] = "******************";
                    this.mUIItemEdit.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        
        public WinGroup UIAllWork1sGoogleChromGroup
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromGroup == null))
                {
                    this.mUIAllWork1sGoogleChromGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIAllWork1sGoogleChromGroup.SearchProperties[WinControl.PropertyNames.Instance] = "3";
                    this.mUIAllWork1sGoogleChromGroup.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllWork1sGoogleChromGroup;
            }
        }
        
        public WinEdit UIAllwork1sgmailcomEdit
        {
            get
            {
                if ((this.mUIAllwork1sgmailcomEdit == null))
                {
                    this.mUIAllwork1sgmailcomEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAllwork1sgmailcomEdit.SearchProperties[WinEdit.PropertyNames.Name] = "allwork1s@gmail.com";
                    this.mUIAllwork1sgmailcomEdit.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllwork1sgmailcomEdit;
            }
        }
        
        public WinGroup UIAllWork1sGoogleChromGroup1
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromGroup1 == null))
                {
                    this.mUIAllWork1sGoogleChromGroup1 = new WinGroup(this);
                    #region Search Criteria
                    this.mUIAllWork1sGoogleChromGroup1.SearchProperties[WinControl.PropertyNames.Instance] = "4";
                    this.mUIAllWork1sGoogleChromGroup1.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllWork1sGoogleChromGroup1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        
        private WinGroup mUIAllWork1sGoogleChromGroup;
        
        private WinEdit mUIAllwork1sgmailcomEdit;
        
        private WinGroup mUIAllWork1sGoogleChromGroup1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIỨngViênTanhuynh1999MenuButton : WinControl
    {
        
        public UIỨngViênTanhuynh1999MenuButton(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Ứng Viên: Tanhuynh1999";
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "MenuButton";
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAllWork1sGoogleChromText
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromText == null))
                {
                    this.mUIAllWork1sGoogleChromText = new WinText(this);
                    #region Search Criteria
                    this.mUIAllWork1sGoogleChromText.SearchProperties[WinText.PropertyNames.Name] = "Ứng Viên: Tanhuynh1999";
                    this.mUIAllWork1sGoogleChromText.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllWork1sGoogleChromText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAllWork1sGoogleChromText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "16.0.29514.35")]
    public class UIĐăngxuấtHyperlink : WinHyperlink
    {
        
        public UIĐăngxuấtHyperlink(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinHyperlink.PropertyNames.Name] = " Đăng xuất";
            this.WindowTitles.Add("AllWork1s - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinText UIAllWork1sGoogleChromText
        {
            get
            {
                if ((this.mUIAllWork1sGoogleChromText == null))
                {
                    this.mUIAllWork1sGoogleChromText = new WinText(this);
                    #region Search Criteria
                    this.mUIAllWork1sGoogleChromText.SearchProperties[WinText.PropertyNames.Name] = "Đăng xuất";
                    this.mUIAllWork1sGoogleChromText.WindowTitles.Add("AllWork1s - Google Chrome");
                    #endregion
                }
                return this.mUIAllWork1sGoogleChromText;
            }
        }
        #endregion
        
        #region Fields
        private WinText mUIAllWork1sGoogleChromText;
        #endregion
    }
}
